name: Publish New Release

on:
  push:
    tags: "v*"
  workflow_dispatch:

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    outputs:
      draft_release: ${{ steps.get_tag.outputs.draft_release }}
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag, release mode
        shell: bash
        id: get_tag
        run: |
          if [[ ${GITHUB_REF##*/} =~ ^v[0-9]\.[0-9]\.[0-9]$ ]];
          then
              draft_release=false
          
          elif [[ ${GITHUB_REF##*/} =~ ^v[0-9]\.[0-9]\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?(\+[A-Za-z0-9.]+)?$ ]];
          then
              draft_release=true
          else
              echo "Existing, github ref needs to be a tag with format vx.y.z or vx.y.z+(alpha|beta|rc)"
              exit 1

          echo "::set-output name=draft_release::${draft_release}"
          echo "::set-output name=tag::$${GITHUB_REF##*/}"

  run_build_workflow:
    runs-on: ubuntu-latest
    needs: validate_tag
    steps:
      - name: Build projects
        uses: ./.github/workflows/build

  release_to_github:
    runs-on: ubuntu-latest
    needs:
      - validate_tag
      - run_build_workflow
    env:
      DRAFT_RELEASE: '${{ needs.validate_tag.outputs.draft_release }}'
      TAG: '${{ needs.validate_tag.outputs.tag }}'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: '${{ env.DRAFT_RELEASE }}'
          fail_on_unmatched_files: true
          name: 'Stream Reactor ${{ env.TAG }}'
          files: |
            /tmp/artifacts/*
